### ISSUE TITLE
Config file

### ISSUE THREAD

**Issue by JeffWScott** [coderaiser/coderaiser.github.io#3]
I have Cloud Commander installed in Ubuntu.

I installed it globally with NPM but I am unable to figure out where the config file is.  I'm not sure where "~/.cloudcmd.json" is because i'm not sure what home directory it's referring to.  I changed the port in /usr/lib/node_modules/cloudcmd/json/config.json but when I restarted the app it still used the default 8000 port so I assume that is the wrong file.

Also, can I change the username and password directly in the config file to avoid having to use the flags when starting up cloudcmd?

BTW, this project is FANTASTIC and I hope you continue to add features.  I love how lightweight and easy to install it was!  I would love to contribute (if I could)!

One more question would be, is it possible to select multiple files/folders on a mobile device?  I only found out how using the spacebar on a desktop and can't figure out the equivalent on a phone.

**Comment by coderaiser** [comment]
- Place for issues. [Issues of Cloud Commander](https://github.com/coderaiser/cloudcmd/issues) is a better place to create issues related to file manager.

- Home directory. There is a lot ways to determine your home directory, one of them is:
```sh
node -e 'console.log(process.env.HOME)'
```
Another one is:
```sh
echo $HOME
```
- Config. If you'd like to change some configuration you can use command line flags this way:
```sh
cloudcmd --port 1234 --username JeffWScott --password anypassword --save
```
You do not need to edit `config.json` by your hands, you better use flags. Last one `--save` will write down all options in `config.json` file and you won't need to set them every time.

You can change options in configuration window, that opens with `F10` button key, as well.
- New features. Thank you. I appreciate every comment and try do my best.
- Select multiple files/folders on mobile device. It's good idea for new feature. I will think about it, it could be very useful actually.

**Comment by JeffWScott** [comment]
Thank you!
