### ISSUE TITLE
When using prefix, the api does not get affected

### ISSUE THREAD

**Issue by moesingh** [coderaiser/coderaiser.github.io#4]
e.g. once you use the --prefix command, then although the system runs on /prefix, it still tries to grab stuff from /api

this means that if you do a httpd proxy-pass from one server to another, that it will show javascript errors when you try to download something unless you include the /api along with the /prefix proxy passes.  

not sure why the api isn't being found on /prefix/api rather than /api for the server location...

**Comment by moesingh** [comment]
ok, so it looks like it does work, but there's something going on in the code.  e.g.

for prefix "prefix"

https://domain/prefix/api/v1/fs/somefile.zip?download 

actually does indeed work, but for some reason, cloudcmd tries to download via this location:

https://domain/api/v1/fs/somefile.zip?download 

so basically, it's ignoring the prefix....  

basically, in the /package/lib/client directory, there are commands that get the apiURL, which is not generating right...

**Comment by moesingh** [comment]
it's in the lib/cloudfunc.js file, where it says this.api_url='/api/v1' which ignores completely the prefix...  

i've just lazily hardcoded the prefix on my end, and dropped the /api proxy pass for now.

**Comment by moesingh** [comment]
hardcoding in cloudfunc.js didn' t work...

**Comment by coderaiser** [comment]
Closed in favour of https://github.com/coderaiser/cloudcmd/issues/51
